name: Create Environment 
on:
  create

env:
  APP_NAME: 'Hello3-${{ github.ref_name }}'

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "create"
        run: echo "Creating Environment ${{ github.ref_name }}"
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create Resource Group
        run: |
          if [ $(az group exists --name "${{ env.APP_NAME }}") = false ]; then
            az group create --name "${{ env.APP_NAME }}" --location "West US"
          fi 
