# Licensed to Werner Strydom under one or more agreements.
# Werner Strydom licenses this file to you under the MIT license.
#
# This deleted Azure resources that were created. It's important that 
# RG_NAME must match that found in branch-build.yml. Remember that this
# runs within the context of the default branch, while branch-build is 
# running within the context of the branch.

name: Delete Environment
on:
  delete

env:
  RG_NAME: 'Hello-Phoenix-Branch-${{ github.event.ref }}'

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Delete Resource Group
        run: |
          if [ $(az group exists --name "${{ env.RG_NAME }}") = true ]; then
            az group delete --name "${{ env.RG_NAME }}" --yes 
          fi 